chore: Ran prettier

diff --git a/.github/workflows/go.yaml b/.github/workflows/go.yaml
--- a/.github/workflows/go.yaml
+++ b/.github/workflows/go.yaml
@@ -19,20 +19,20 @@ jobs:
       run:
         working-directory: ./cx-content-moderation
     steps:
-    - name: Setup Go
-      uses: actions/setup-go@v4
-      with:
-        go-version: '^1.20'
-    - name: Checkout code
-      uses: actions/checkout@v3
-    - name: Build code
-      # Use find to build all modules. '-execdir ... ;' doesn't set an exit code
-      # based on command results. So, create a file if a build fails and check
-      # if the file exists to set the right exit code.
-      run: |
-        ROOT_DIR=$(pwd) \
-        find . -name go.mod -execdir sh -c 'go build ./... || touch $ROOT_DIR/build_failed.txt' \; ; \
-        test ! -f build_failed.txt
+      - name: Setup Go
+        uses: actions/setup-go@v4
+        with:
+          go-version: "^1.20"
+      - name: Checkout code
+        uses: actions/checkout@v3
+      - name: Build code
+        # Use find to build all modules. '-execdir ... ;' doesn't set an exit code
+        # based on command results. So, create a file if a build fails and check
+        # if the file exists to set the right exit code.
+        run: |
+          ROOT_DIR=$(pwd) \
+          find . -name go.mod -execdir sh -c 'go build ./... || touch $ROOT_DIR/build_failed.txt' \; ; \
+          test ! -f build_failed.txt
   lint:
     name: Lint
     runs-on: ubuntu-latest
@@ -40,27 +40,27 @@ jobs:
       run:
         working-directory: ./cx-content-moderation
     steps:
-    - name: Setup Go
-      uses: actions/setup-go@v4
-      with:
-        go-version: '^1.20'
-    - name: Checkout code
-      uses: actions/checkout@v3
-    - name: Install goimports
-      run: go install golang.org/x/tools/cmd/goimports@latest
-    - run: goimports -w .
-    - name: Run go mod tidy on all modules
-      run: find . -name go.mod -execdir go mod tidy \;
-    # If there are any diffs from goimports or go mod tidy, fail.
-    - name: Verify no changes from goimports and go mod tidy.
-      run: |
-        if [ -n "$(git status --porcelain)" ]; then
-          echo 'To fix this check, run "goimports -w . && find . -name go.mod -execdir go mod tidy \;"'
-          git status # Show the files that failed to pass the check.
-          exit 1
-        fi
-    - name: shellcheck
-      run: find . -name "*.sh" -exec shellcheck {} \;
+      - name: Setup Go
+        uses: actions/setup-go@v4
+        with:
+          go-version: "^1.20"
+      - name: Checkout code
+        uses: actions/checkout@v3
+      - name: Install goimports
+        run: go install golang.org/x/tools/cmd/goimports@latest
+      - run: goimports -w .
+      - name: Run go mod tidy on all modules
+        run: find . -name go.mod -execdir go mod tidy \;
+      # If there are any diffs from goimports or go mod tidy, fail.
+      - name: Verify no changes from goimports and go mod tidy.
+        run: |
+          if [ -n "$(git status --porcelain)" ]; then
+            echo 'To fix this check, run "goimports -w . && find . -name go.mod -execdir go mod tidy \;"'
+            git status # Show the files that failed to pass the check.
+            exit 1
+          fi
+      - name: shellcheck
+        run: find . -name "*.sh" -exec shellcheck {} \;
   vet:
     name: Vet
     runs-on: ubuntu-latest
@@ -68,20 +68,20 @@ jobs:
       run:
         working-directory: ./cx-content-moderation
     steps:
-    - name: Setup Go
-      uses: actions/setup-go@v4
-      with:
-        go-version: '^1.20'
-    - name: Checkout code
-      uses: actions/checkout@v3
-    - name: go vet
-      # Use find to build all modules. '-execdir ... ;' doesn't set an exit code
-      # based on command results. So, create a file if a build fails and check
-      # if the file exists to set the right exit code.
-      run: |
-        ROOT_DIR=$(pwd) \
-        find . -name go.mod -execdir sh -c 'go vet ./... || touch $ROOT_DIR/vet_failed.txt' \; ; \
-        test ! -f vet_failed.txt
+      - name: Setup Go
+        uses: actions/setup-go@v4
+        with:
+          go-version: "^1.20"
+      - name: Checkout code
+        uses: actions/checkout@v3
+      - name: go vet
+        # Use find to build all modules. '-execdir ... ;' doesn't set an exit code
+        # based on command results. So, create a file if a build fails and check
+        # if the file exists to set the right exit code.
+        run: |
+          ROOT_DIR=$(pwd) \
+          find . -name go.mod -execdir sh -c 'go vet ./... || touch $ROOT_DIR/vet_failed.txt' \; ; \
+          test ! -f vet_failed.txt
   test:
     name: Root tests
     runs-on: ubuntu-latest
@@ -92,7 +92,7 @@ jobs:
       - name: Setup Go
         uses: actions/setup-go@v4
         with:
-          go-version: '^1.20'
+          go-version: "^1.20"
       - name: Check code
         uses: actions/checkout@v3
       - run: go test -v
